version: '3'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: container-front-projet-angular
    ports:
      - 82:80
    depends_on:
      - jsonserver
    volumes:
      - ./dist/projettest_angular/:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - projet_network

  jsonserver:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: container-json-server
    ports:
      - 8089:8089
    volumes:
      - ./data:/app/data
    networks:
      - projet_network

networks:
  projet_network:
    driver: bridge
